name: ML Application CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        tags: my_ml_app:latest

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Load Docker image
      uses: docker/setup-buildx-action@v1

    - name: Docker Run
      run: |
        docker run my_ml_app:latest pytest ./src/tests

  validate:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Load Docker image
      uses: docker/setup-buildx-action@v1

    - name: Validate Model
      run: |
        docker run my_ml_app:latest python -m src.model.validate
